name: Bug report
description: Report a bug in the project
title: "[BUG] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: Provide steps to reproduce the issue

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior

  - type: input
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: Describe the actual behavior

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: The environment in which the bug was observed.
      options:
        - Windows
        - macOS
        - Linux
        - Other
